package com.kyuusanq3.mixauto.ui.dashboard

import com.kyuusanq3.mixauto.data.apps.LaunchableAppEntry
import com.kyuusanq3.mixauto.domain.map.CarMapEngine
import com.kyuusanq3.mixauto.domain.map.SearchResultPlace
import com.kyuusanq3.mixauto.domain.media.MediaPlaybackState
import com.kyuusanq3.mixauto.ui.settings.AppUpdateState
import com.kyuusanq3.mixauto.ui.settings.MapDataViewModel
import java.io.File

internal data class DashboardMapPaneProps(
    val mapEngine: CarMapEngine,
    val onToggleSearch: () -> Unit,
    val isDestinationPanelOpen: Boolean,
    val onToggleMapSettings: () -> Unit,
    val isMapSettingsPanelOpen: Boolean,
    val reduceTopInsetBelowStatusStrip: Boolean,
)

internal data class DashboardSecondaryPaneProps(
    val activePanel: ActivePanel,
    val mapEngine: CarMapEngine,
    val mapDataViewModel: MapDataViewModel,
    val onDismissPanel: () -> Unit,
    val onOpenMapData: () -> Unit,
    val onPreviewSearchPlace: (SearchResultPlace) -> Unit,
    val onOpenAddFromLink: () -> Unit,
    val onDismissAddPlacePanel: () -> Unit,
    val onConfirmAddPlaceFromLink: (SearchResultPlace) -> Unit,
    val recentDestinations: List<SearchResultPlace>,
    val savedPlaces: List<SearchResultPlace>,
    val onDestinationSelected: (SearchResultPlace) -> Unit,
    val onToggleSavedPlace: (SearchResultPlace) -> Unit,
    val onUpdateSavedPlace: (SearchResultPlace) -> Unit,
    val onClearPoiReturnToSearch: () -> Unit,
    val mediaState: MediaPlaybackState,
    val defaultAudioPackage: String,
    val onSetDefaultAudioPackage: (String) -> Unit,
    val onMediaPlayPause: () -> Unit,
    val onMediaSkipPrevious: () -> Unit,
    val onMediaSkipNext: () -> Unit,
    val onMediaToggleLike: () -> Unit,
    val albumArtMode: AlbumArtMode,
    val onAlbumArtModeChange: (AlbumArtMode) -> Unit,
    val isLeftHandDrive: Boolean,
    val isShortcutsHorizontal: Boolean,
    val limitSearchDistance: Boolean,
    val useVectorTiles: Boolean,
    val show3dBuildings: Boolean,
    val showTraffic: Boolean,
    val navigationVoiceEnabled: Boolean,
    val navigationVoiceVolume: Float,
    val tomTomApiKey: String,
    val isLauncherMode: Boolean,
    val shortcutIconSize: DockShortcutIconSize,
    val drivingZoom: Float,
    val drivingTilt: Float,
    val puckHorizontalOffset: Float,
    val puckVerticalOffset: Float,
    val onToggleLhd: () -> Unit,
    val onToggleShortcutsHorizontal: () -> Unit,
    val onToggleLimitSearchDistance: () -> Unit,
    val onToggleVectorTiles: () -> Unit,
    val onToggleShow3dBuildings: () -> Unit,
    val onToggleTraffic: () -> Unit,
    val onToggleNavigationVoice: () -> Unit,
    val onNavigationVoiceVolumeChange: (Float) -> Unit,
    val onTestNavigationVoice: () -> Unit,
    val onTomTomApiKeyChange: (String) -> Unit,
    val onToggleLauncherMode: () -> Unit,
    val onShortcutIconSizeChange: (DockShortcutIconSize) -> Unit,
    val onDrivingZoomChange: (Float) -> Unit,
    val onDrivingTiltChange: (Float) -> Unit,
    val onPuckHorizontalOffsetChange: (Float) -> Unit,
    val onPuckVerticalOffsetChange: (Float) -> Unit,
    val puckScale: Float,
    val onPuckScaleChange: (Float) -> Unit,
    val showStatusStrip: Boolean,
    val showSystemStatusBar: Boolean,
    val onToggleShowStatusStrip: () -> Unit,
    val onToggleShowSystemStatusBar: () -> Unit,
    val reduceMediaTopInsetBelowStatusStrip: Boolean,
    val appUpdateState: AppUpdateState,
    val onCheckForUpdate: () -> Unit,
    val onDownloadUpdate: () -> Unit,
    val onInstallApk: (File) -> Unit,
    val isAudioPlayerMinimized: Boolean,
    val onToggleAudioPlayerMinimized: () -> Unit,
    val isPortrait: Boolean,
)

internal data class DashboardDockProps(
    val shortcutIconSize: DockShortcutIconSize,
    val isLeftHandDrive: Boolean,
    val activePanel: ActivePanel,
    val mediaState: MediaPlaybackState,
    val voiceSearchAvailable: Boolean,
    val dockPinnedPackages: List<String>,
    val onToggleDockPin: (String) -> Unit,
    val onTogglePanel: (ActivePanel) -> Unit,
    val onVoiceSearch: () -> Unit,
)

internal data class DashboardAppDrawerProps(
    val activePanel: ActivePanel,
    val launchableApps: List<LaunchableAppEntry>,
    val isAppDrawerLoading: Boolean,
    val dockPinnedPackages: List<String>,
    val onToggleDockPin: (String) -> Unit,
    val onOpenLauncherSettings: () -> Unit,
    val onDismiss: () -> Unit,
)

internal data class DashboardLayoutProps(
    val map: DashboardMapPaneProps,
    val secondaryPane: DashboardSecondaryPaneProps,
    val dock: DashboardDockProps,
    val appDrawer: DashboardAppDrawerProps,
    val showSecondaryPane: Boolean,
    val showMapMediaDivider: Boolean,
    val effectiveMapMediaRatio: Float,
    val effectiveMediaWeight: Float,
    val mapMediaRatio: Float,
    val onMapMediaRatioChange: (Float) -> Unit,
    val isLeftHandDrive: Boolean,
)
